name: Build and publish backend

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main
      - feature/github-actions-workflows

jobs:
  # -------------------------------------------------------------
  # Using GitHub's API is not supported for push events
  # -------------------------------------------------------------
  #
  # ----------------------------------------------------------------------------------------------
  # Using local .git history
  # ----------------------------------------------------------------------------------------------
  # Event `push`: Compare the preceding remote commit -> to the current commit of the main branch
  # ----------------------------------------------------------------------------------------------
  changed_files:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Test changed-files
    outputs:
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        with:
          dir_names: 'true'
          dir_names_max_depth: '2'
          dir_names_exclude_current_dir: 'true'
          matrix: 'true'
          files_ignore: |
            backend/README.md
            .github/**
            frontend/**
            docker-resources/**
            gradle/**
        uses: tj-actions/changed-files@v45
      # NOTE: `since_last_remote_commit: true` is implied by default and falls back to the previous local commit.

  Build-and-publish:
    runs-on: ubuntu-latest
    needs: changed_files
    strategy:
      matrix:
        value: ${{ fromJSON(needs.changed_files.outputs.matrix) }}
    name: Build and publish

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Listing changed plugin folders
        run: echo ${{ matrix.value }}

      - id: gradleTaskAlize
        name: Construct Gradle task name from matrix variant
        run: CHANGED_DIR=${{ matrix.value }}; echo "TASK_NAME=$(echo :$CHANGED_DIR:publishToCentralPortal | sed -e 's/\//:/g')">>${GITHUB_OUTPUT}
        env:
          CHANGED_DIR: ${{ matrix.value }}

      - name: Publish
        run: ./gradlew ${{ steps.gradleTaskAlize.outputs.TASK_NAME }}

