name: Build and publish frontend

on:
  push:
    paths:
      - 'frontend/**'
    branches:
      - main
      - feature/github-actions-workflows

jobs:
  # -------------------------------------------------------------
  # Using GitHub's API is not supported for push events
  # -------------------------------------------------------------
  #
  # ----------------------------------------------------------------------------------------------
  # Using local .git history
  # ----------------------------------------------------------------------------------------------
  # Event `push`: Compare the preceding remote commit -> to the current commit of the main branch
  # ----------------------------------------------------------------------------------------------
  changed_files:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Test changed-files
    outputs:
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        with:
          dir_names: 'true'
          dir_names_max_depth: '2'
          matrix: 'true'
          path: 'frontend/projects'
        uses: tj-actions/changed-files@v45
      # NOTE: `since_last_remote_commit: true` is implied by default and falls back to the previous local commit.

  Build-and-publish:
    runs-on: ubuntu-latest
    needs: changed_files
    strategy:
      matrix:
        value: ${{ fromJSON(needs.changed_files.outputs.matrix) }}
    name: Build and publish

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install --global @angular/cli
        working-directory: frontend
      - run: npm install --legacy-peer-deps
        working-directory: frontend

      - id: constructBuildTask
        name: Construct build task name from matrix variant
        run: CHANGED_DIR=${{ matrix.value }}; PLUGIN=$(echo $CHANGED_DIR | sed 's/.*\///'); echo "TASK_NAME=$(echo libs:build:$PLUGIN)">>${GITHUB_OUTPUT}
        env:
          CHANGED_DIR: ${{ matrix.value }}

      - run: npm run ${TASK_NAME}
        working-directory: frontend
      - run: npm --prefix . run libs-publish-all -- npmjs ${{ secrets.NPMJS_SECRET }}
        working-directory: frontend
